Fix `BaseStreamTestCase`
Multiple `ReplicationCommandHandler` were getting created for the same HS
registering the hook twice

```
2025-08-07 18:38:14-0500 [-] synapse.replication.tcp.handler - 386 - ERROR - process-replication-data-11 - Failed to handle command <synapse.replication.tcp.commands.PositionCommand object at 0x7fb5fbe04320>
	Traceback (most recent call last):
	  File "synapse/replication/tcp/handler.py", line 384, in _unsafe_process_queue
	    await self._process_command(cmd, conn, stream_name)
	  File "synapse/replication/tcp/handler.py", line 397, in _process_command
	    await self._process_position(stream_name, conn, cmd)
	  File "synapse/replication/tcp/handler.py", line 721, in _process_position
	    (updates, current_token, missing_updates) = await stream.get_updates_since(
	                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	        cmd.instance_name, current_token, cmd.new_token
	        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	    )
	    ^
	  File "synapse/replication/tcp/streams/_base.py", line 213, in get_updates_since
	    updates, upto_token, limited = await self.update_function(
	                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
	    ...<4 lines>...
	    )
	    ^
	  File "synapse/replication/tcp/streams/_base.py", line 269, in update_function
	    result = await client(
	             ^^^^^^^^^^^^^
	    ...<4 lines>...
	    )
	    ^
	  File "synapse/logging/opentracing.py", line 929, in _wrapper
	    return await func(*args, **kwargs)
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "synapse/replication/http/_base.py", line 232, in send_request
	    streams = hs.get_replication_command_handler().get_streams_to_replicate()
	              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
	  File "synapse/server.py", line 232, in _get
	    dep = builder(self)
	  File "synapse/server.py", line 756, in get_replication_command_handler
	    return ReplicationCommandHandler(self)
	  File "synapse/replication/tcp/handler.py", line 258, in __init__
	    tcp_resource_total_connections_gauge.register_hook(
	    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
	        homeserver_instance_id=hs.get_instance_id(),
	        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	        hook=lambda: {(self.server_name,): len(self._connections)},
	        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	    )
	    ^
	  File "synapse/metrics/__init__.py", line 225, in register_hook
	    assert existing_hook is None, (
	           ^^^^^^^^^^^^^^^^^^^^^
	AssertionError: LaterGauge(name=synapse_replication_tcp_resource_total_connections) hook already registered for homeserver_instance_id=gZBmA. This is likely a Synapse bug and you forgot to unregister the previous hooks for the server (especially in tests).
```