Ignore suspended users failing when trying to shutdown room (joining new room) (#20283)
Our admin API to delete a room has a weird feature where you can supply
`new_room_user_id` and it will create a new room and join all of the
users to that room:

https://github.com/element-hq/synapse/blob/929e3524d189bf7d3402866b930cebde6bb54892/docs/admin_api/rooms.md#L640-L642

But that room can contain [suspended
users](https://spec.matrix.org/v1.19/client-server-api/#account-suspension)
which are unable to join new rooms. Currently, we use
`logger.exception(...)` for this failure which ends up in Sentry but
since this is probably expected outcome and we shouldn't elevate it to
that level of problem as it's just noise.

Spawning from seeing the error in Sentry,
https://sentry.tools.element.io/organizations/element/issues/11266279/?project=2
```
Traceback (most recent call last):
  File "synapse/handlers/room.py", line 2532, in shutdown_room
    await self.room_member_handler.update_membership(
  File "synapse/handlers/room_member.py", line 675, in update_membership
    result = await self.update_membership_locked(
  File "synapse/handlers/room_member.py", line 794, in update_membership_locked
    raise SynapseError(
SynapseError: 403: Joining rooms while account is suspended is not allowed.
```