pass an instance, not a type, to resolveHostName
resolveHostName wanted an instance of a type. We also had to switch from provider to
implementer, as the latter implies that any instances implement the given interface.

Fixed the following error:

synapse/http/client.py:243: error: Argument 1 to "resolveHostName" of "IHostnameResolver" has incompatible type "type[EndpointReceiver]"; expected "IResolutionReceiver"  [arg-type]