Use `Box` so the size is known and because the `db_pool` is not shared
```
error[E0277]: the size for values of type `(dyn storage::db::DatabasePool + 'static)` cannot be known at compilation time
  --> rust/src/handlers/mod.rs:53:30
   |
53 |         let store = Arc::new(Store { config, db_pool });
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
   |
   = help: within `storage::store::Store`, the trait `std::marker::Sized` is not implemented for `(dyn storage::db::DatabasePool + 'static)`
note: required because it appears within the type `storage::store::Store`
  --> rust/src/storage/store.rs:37:12
   |
37 | pub struct Store {
   |            ^^^^^
   = note: structs must have a statically known size to be initialized
```