Fix `self.server_name` missing because super constructor didn't run yet
```
SYNAPSE_TEST_LOG_LEVEL=INFO poetry run trial tests.test_server.OptionsResourceTests.test_known_request
The "poetry.dev-dependencies" section is deprecated and will be removed in a future version. Use "poetry.group.dev.dependencies" instead.
tests.test_server
  OptionsResourceTests
    test_known_request ...                                              [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/eric/Documents/github/element/synapse/tests/unittest.py", line 131, in new
    return code(orig, *args, **kwargs)
  File "/home/eric/Documents/github/element/synapse/tests/unittest.py", line 225, in setUp
    return orig()
  File "/home/eric/Documents/github/element/synapse/tests/test_server.py", line 219, in setUp
    self.homeserver = setup_test_homeserver(
  File "/home/eric/Documents/github/element/synapse/tests/server.py", line 1147, in setup_test_homeserver
    hs.setup()
  File "synapse/server.py", line 361, in setup
    self.datastores = Databases(self.DATASTORE_CLASS, self)
  File "synapse/storage/databases/__init__.py", line 104, in __init__
    main = main_store_class(database, db_conn, hs)
  File "synapse/storage/databases/main/__init__.py", line 174, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/events_bg_updates.py", line 122, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/experimental_features.py", line 44, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/devices.py", line 1776, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/devices.py", line 95, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/roommember.py", line 2030, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/room.py", line 2449, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/room.py", line 2023, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/room.py", line 152, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/registration.py", line 2519, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/registration.py", line 2407, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/profile.py", line 53, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/presence.py", line 80, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/presence.py", line 61, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/transactions.py", line 81, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/state.py", line 974, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/state.py", line 118, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/state.py", line 765, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/event_federation.py", line 2094, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/media_repository.py", line 226, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/media_repository.py", line 119, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/filtering.py", line 49, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/event_push_actions.py", line 1894, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/metrics.py", line 75, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/event_push_actions.py", line 263, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/end_to_end_keys.py", line 1551, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/e2e_room_keys.py", line 69, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/search.py", line 436, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/search.py", line 145, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/account_data.py", line 68, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/push_rule.py", line 138, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/appservice.py", line 103, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/pusher.py", line 82, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/roommember.py", line 102, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/pusher.py", line 579, in __init__
    super().__init__(database, db_conn, hs)
  File "synapse/storage/databases/main/receipts.py", line 142, in __init__
    server_name=self.server_name,
builtins.AttributeError: 'DataStore' object has no attribute 'server_name'

tests.test_server.OptionsResourceTests.test_known_request
-------------------------------------------------------------------------------
Ran 1 tests in 0.094s

FAILED (errors=1)
```