Use new private variable for hostname as str
`._hostStr` was replaced with `._hostText` in https://github.com/twisted/twisted/pull/12351

Resolves the following errors:

tests/http/test_proxyagent.py:857: error: "HostnameEndpoint" has no attribute "_hostStr"  [attr-defined]
tests/http/test_proxyagent.py:869: error: "HostnameEndpoint" has no attribute "_hostStr"  [attr-defined]