Resolve `fetchall` lifetimes -> `FromPyObjectOwned`
We can use `FromPyObjectOwned` (instead of `FromPyObject`)
because we don't borrow anything

```
error[E0107]: trait takes 2 lifetime arguments but 1 lifetime argument was supplied
   --> rust/src/storage/db/python_db_pool.rs:220:24
    |
220 |     pub fn fetchall<T: FromPyObject<'py> + ValidDatabaseReturnType>(
    |                        ^^^^^^^^^^^^ --- supplied 1 lifetime argument
    |                        |
    |                        expected 2 lifetime arguments
    |
note: trait defined here, with 2 lifetime parameters: `'a`, `'py`
   --> /home/eric/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.28.3/src/conversion.rs:401:11
    |
401 | pub trait FromPyObject<'a, 'py>: Sized {
    |           ^^^^^^^^^^^^ --  ---
help: add missing lifetime argument
    |
220 |     pub fn fetchall<T: FromPyObject<'py, 'py> + ValidDatabaseReturnType>(
    |                                        +++++
```