Fix `server_name` missing in `RedisSubscriber` (complexity)
See https://github.com/element-hq/synapse/pull/18670#discussion_r2212034737

Error:

```
  File "/home/runner/work/synapse/synapse/synapse/replication/tcp/redis.py", line 127, in __init__
    name="replication_command_handler", server_name=self.server_name
builtins.AttributeError: 'RedisSubscriber' object has no attribute 'server_name'
```

`self.server_name` is not set in the constructor since we set this after it's created, see
https://github.com/element-hq/synapse/blob/06108100c848ab3f6b9e541b7769bbc63adc2bf6/synapse/replication/tcp/redis.py#L383-L391